// This file contains the test dates. To be updated frequently.
export const regularDates = [
    { date: 'Friday, 03 October', venues: 4, capacity: { withLaptop: 70, withoutLaptop: 30 } },
    { date: 'Friday, 10 October', venues: 4, capacity: { withLaptop: 70, withoutLaptop: 30 } },
    { date: 'Friday, 17 October', venues: 4, capacity: { withLaptop: 70, withoutLaptop: 30 } },
    { date: 'Friday, 24 October', venues: 4, capacity: { withLaptop: 70, withoutLaptop: 30 } },
    { date: 'Friday, 07 November', venues: 4, capacity: { withLaptop: 70, withoutLaptop: 30 } },
    { date: 'Friday, 14 November', venues: 4, capacity: { withLaptop: 70, withoutLaptop: 30 } },
    { date: 'Wednesday, 19 November', venues: 4, capacity: { withLaptop: 70, withoutLaptop: 30 } },
    { date: 'Friday, 21 November', venues: 4, capacity: { withLaptop: 70, withoutLaptop: 30 } },
    { date: 'Friday, 28 November', venues: 4, capacity: { withLaptop: 70, withoutLaptop: 30 } },
    { date: 'Friday, 05 December', venues: 4, capacity: { withLaptop: 70, withoutLaptop: 30 } },
    { date: 'Wednesday, 10 December', venues: 4, capacity: { withLaptop: 70, withoutLaptop: 30 } },
    { date: 'Friday, 12 December', venues: 4, capacity: { withLaptop: 70, withoutLaptop: 30 } },
    { date: 'Wednesday, 14 January', venues: 4, capacity: { withLaptop: 70, withoutLaptop: 30 } },
    { date: 'Friday, 06 February', venues: 4, capacity: { withLaptop: 70, withoutLaptop: 30 } },
    { date: 'Friday, 13 February', venues: 4, capacity: { withLaptop: 70, withoutLaptop: 30 } },
    { date: 'Friday, 20 February', venues: 4, capacity: { withLaptop: 70, withoutLaptop: 30 } },
    { date: 'Friday, 27 February', venues: 4, capacity: { withLaptop: 70, withoutLaptop: 30 } },
    { date: 'Friday, 06 March', venues: 4, capacity: { withLaptop: 70, withoutLaptop: 30 } },
    { date: 'Friday, 13 March', venues: 4, capacity: { withLaptop: 70, withoutLaptop: 30 } },
    { date: 'Friday, 20 March', venues: 4, capacity: { withLaptop: 70, withoutLaptop: 30 } },
    { date: 'Friday, 27 March', venues: 4, capacity: { withLaptop: 70, withoutLaptop: 30 } },
    { date: 'Friday, 03 April', venues: 4, capacity: { withLaptop: 70, withoutLaptop: 30 } },
    { date: 'Friday, 17 April', venues: 4, capacity: { withLaptop: 70, withoutLaptop: 30 } },
    { date: 'Friday, 24 April', venues: 4, capacity: { withLaptop: 70, withoutLaptop: 30 } },
    { date: 'Tueday, 28 April', venues: 4, capacity: { withLaptop: 70, withoutLaptop: 30 } },
  ];
